name: nightlife
main: com.scarlettparker.nightlife.Plugin
version: 1.1.6
api-version: 1.15
description: Night Life plugin for Video Games Society.
commands:
  help:
    description: "Night Life help command."
    usage: "/<command>"
  plugins:
    description: "List all plugins."
    aliases: [pl]
    usage: "/<command>"
  tell:
    description: "Tell a player something."
    aliases: [msg, w, tellraw]
    usage: "/<command> <player> <message>"
  boogey:
    description: "Set the boogeyman."
    usage: "/<command> <number|player>"
  cure:
    description: "Cure a player."
    usage: "/<command> <player>"
  punish:
    description: "Punish a player."
    usage: "/<command> <player>"
  startlife:
    description: "Start the life series."
    usage: "/<command>"
  setlife:
    description: "Set a player's lives."
    usage: "/<command> <player> <lives>"